server {
    listen 8080;

    location = /h5n1 {
        return 308 /h5n1/;
    }

    location /h5n1/ {
        rewrite ^/h5n1/(.*)$ /$1 break;
        proxy_pass http://lapis-h5n1:8080;
    }

    location = /rsv-a {
        return 308 /rsv-a/;
    }

    location /rsv-a/ {
        rewrite ^/rsv-a/(.*)$ /$1 break;
        proxy_pass http://lapis-rsv-a:8080;
    }
}
