schema:
  instanceName: RSV A
  opennessLevel: OPEN
  metadata:
  - type: string
    name: accessionVersion
  - type: string
    name: accession
  - type: int
    name: version
  - type: string
    name: submissionId
  - type: boolean
    name: isRevocation
  - type: string
    generateIndex: true
    name: submitter
  - type: string
    generateIndex: true
    name: groupName
  - type: int
    name: groupId
  - type: int
    name: submittedAtTimestamp
  - type: string
    generateIndex: true
    name: submittedDate
  - type: int
    name: releasedAtTimestamp
  - type: string
    generateIndex: true
    name: releasedDate
  - type: string
    generateIndex: true
    name: dataUseTerms
  - type: date
    name: dataUseTermsRestrictedUntil
  - type: date
    name: dataBecameOpenAt
  - type: string
    name: dataUseTermsUrl
  - type: string
    name: versionStatus
  - type: int
    name: pipelineVersion
  - type: string
    name: authorAffiliations
  - type: string
    name: authors
  - type: string
    name: bioprojectAccession
  - type: string
    name: biosampleAccession
  - type: float
    name: completeness
  - type: string
    name: frameShifts
  - type: string
    generateIndex: true
    name: geoLocAdmin1
  - type: string
    generateIndex: true
    name: geoLocCountry
  - type: string
    generateIndex: true
    name: hostNameScientific
  - type: string
    name: hostTaxonId
  - type: string
    name: insdcAccessionBase
  - type: string
    name: insdcAccessionFull
  - type: string
    name: insdcRawReadsAccession
  - type: int
    name: insdcVersion
  - type: int
    name: length
  - type: string
    generateIndex: true
    name: lineage
  - type: string
    name: ncbiCompleteness
  - type: int
    name: ncbiProteinCount
  - type: date
    name: ncbiReleaseDate
  - type: string
    generateIndex: true
    name: ncbiSourceDb
  - type: date
    name: ncbiUpdateDate
  - type: string
    generateIndex: true
    name: ncbiVirusName
  - type: int
    name: ncbiVirusTaxId
  - type: string
    name: sampleCollectionDate
  - type: string
    name: specimenCollectorSampleId
  - type: string
    name: stopCodons
  - type: int
    name: totalAmbiguousNucs
  - type: int
    name: totalDeletedNucs
  - type: int
    name: totalFrameShifts
  - type: int
    name: totalInsertedNucs
  - type: int
    name: totalSnps
  - type: int
    name: totalStopCodons
  - type: int
    name: totalUnknownNucs
  primaryKey: accessionVersion
  features:
  - name: generalizedAdvancedQuery
