taxon_id: 10244
organism: mpox
backend_url: http://backend:8079
keycloak_token_url: http://keycloak:8080/realms/loculus/protocol/openid-connect/token
rename:
  bioprojects: bioproject_accessions
  country: geo_loc_country
  division: geo_loc_admin_1
  genbank_accession: insdc_accession_full
  ncbi_collection_date: sample_collection_date
  ncbi_host_name: host_name_scientific
  ncbi_host_tax_id: host_taxon_id
  ncbi_is_lab_host: is_lab_host
  ncbi_isolate_name: specimen_collector_sample_id
  ncbi_sra_accessions: sra_run_accession
  ncbi_submitter_affiliation: author_affiliations
  ncbi_submitter_names: authors
