taxon_id: 208893
nucleotide_sequences:
- main
verify_loculus_version_is: commit-52e855d
check_ena_deposition: false
organism: rsv-a
backend_url: http://backend:8079
keycloak_token_url: http://keycloak:8080/realms/loculus/protocol/openid-connect/token
rename:
  bioprojects: bioprojectAccession
  country: geoLocCountry
  division: geoLocAdmin1
  genbankAccession: insdcAccessionFull
  ncbiCollectionDate: sampleCollectionDate
  ncbiHostName: hostNameScientific
  ncbiHostTaxId: hostTaxonId
  ncbiIsolateName: specimenCollectorSampleId
  ncbiSraAccessions: insdcRawReadsAccession
  ncbiSubmitterAffiliation: authorAffiliations
  ncbiSubmitterNames: authors
insdc_segment_specific_fields:
- insdcAccessionBase
- insdcAccessionFull
- insdcVersion
- ncbiUpdateDate
